

.PHONY: all clean

all:
	
		$(MAKE) -C spu_soundlib
		$(MAKE) -C libogg-1.2.1
		$(MAKE) -C libmpg123
		$(MAKE) -C audioplayerlib
		$(MAKE) -C spu_soundmodule
	

clean:
	
		$(MAKE) clean -C spu_soundlib
		$(MAKE) clean -C libogg-1.2.1
		$(MAKE) clean -C libmpg123
		$(MAKE) clean -C audioplayerlib
		$(MAKE) clean -C spu_soundmodule
	
